apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

# kubectl apply -f rollingupdate-svc.yml

# kubectl apply -f rollingupdate-deploy-v1.yml

# kubectl apply -f rollingupdate-deploy-v2.yml

# kubectl rollout undo deployment/nginx-deployment

# kubectl rollout history deployment/nginx-deployment

# kubectl rollout undo deployment/nginx-deployment --to-revision=<revsion-number>

